### ISSUE TITLE
Question on persisting data with @CommandHandlers

### ISSUE THREAD

**Issue by bjornharvold** [jeroenvanmaanen/ledger-axon#1]
Hi @jeroenvanmaanen!

Thank you for creating this repo. Really well done and organized. I have a question about your use of some of your @CommandHandler methods to persist state using the injected mongoTemplate.

I thought that was a no-no. In most places you take care of persisting state in the @EventHandler methods but I would love some insight into why you did what you did with the command handler methods.

Cheers!

**Comment by jeroenvanmaanen** [comment]
Hi @bjornharvold,

Thanks for your kind words. You are right, persisting state in the command handler methods is a no-no and I will take it right out when I have a better solution for the "duplicate record" exception.

What I did is try to store a unique key in Mongo and have the command handler fail when Mongo reports a duplicate key. I never use this record with the unique key anywhere else in the application, so I had hoped it wouldn't count as 'persisted state', but I agree that it doesn't fully comply with the Event Sourcing way. I just haven't figured out yet how to do this properly. Suggestions welcome!

**Comment by bjornharvold** [comment]
Ah I see. What are the chances of the key not being unique in your case?

**Comment by jeroenvanmaanen** [comment]
I prefer to download my bank transactions from January first every time I download them. That kind of guarantees that (if I don't chop off what I already imported) I start out with a lot of unique key violations. The other problem is that my bank does not supply a unique ID with a transaction, so I concatenate most fields to get an alternate key, but that is too wieldy to be used as an aggregate identifier.

The solutions suggested by AxonIQ (e.g., [in this post](https://groups.google.com/forum/#!topic/axonframework/tCarGj3nXKc) or [in this post](https://groups.google.com/forum/#!topic/axonframework/AIIZNsJVypA)) propose to do what I did: add a table with a unique constraint in the query model.

However, I do agree with you that this is not very elegant, so I devised a way to store this information in a hierarchy of aggregates. I tried to implement it in such a way that it still scales to very large data sets for which it is impractical to keep the entire index in memory. I pushed this to the master a few minutes ago, so please have a look and tell me what you think. I am afraid that this method is quite a bit slower than a database index though. :-(

Oh, and I noticed that in the case of the Account aggregate I did use the data inserted in the Command Handler as a query model. I fixed that now.

**Comment by bjornharvold** [comment]
That makes sense :-) Nicely done. Noting down some of the things you did here and will use these them when I encounter similar issues. Cheers @jeroenvanmaanen!
